---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

AllCops:
  TargetRubyVersion: '3.2'
  Exclude:
    - vendor/**/*
    - .vendor/**/*
    - spec/fixtures/**/*
    - modules/**/*

Style/SymbolProc:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Max: 150

Style/FetchEnvVar:
  Enabled: false