---
name: Docker transport

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker_transport:
    name: Docker Transport
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: [3.2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache modules
        id: modules
        uses: actions/cache@v4
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - uses: ./.github/actions/sudo_setup
      - name: Run tests
        run: bundle exec rake ci:docker_transport
