---
name: Unit tests

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  unit:
    name: "Ruby ${{ matrix.ruby }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
        ruby: ['3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Output Ruby Environment
        run: bundle env
      - name: Cache modules
        id: modules
        uses: actions/cache@v4
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - name: Unit tests
        run: bundle exec rake tests:unit

  tests:
    needs:
      - unit
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - run: echo Test suite complete
