---
name: Windows

on:
  pull_request: {}
  push:
    branches:
      - main

env:
  BOLT_WINRM_USER: roddypiper
  BOLT_WINRM_HOST: localhost
  BOLT_WINRM_PORT: 5985
  BOLT_WINRM_SSL_PORT: 5986
  BOLT_WINRM_SMB_PORT: 445

permissions:
  contents: read

jobs:
  integration:
    name: Integration
    runs-on: windows-2025
    strategy:
      matrix:
        ruby: [3.2]
    env:
      WINDOWS_AGENTS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache modules
        id: modules
        uses: actions/cache@v4
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - name: Output powershell version
        run: $PSVersionTable
      - name: List trusted WSMan hosts
        run: Get-Item WSMan:\localhost\Client\TrustedHosts
      - name: Output WinRM logs
        run: winrm enumerate winrm/config/listener
      - name: Test WSMan connection
        run: Test-WSMan localhost
      - uses: ./.github/actions/windows_agent_setup
      - name: Run test
        run: bundle exec rake ci:windows:integration --trace -v
      - name: Sessions
        if: always()
        run: Get-PSSession
      - name: Test WSMan connection
        if: always()
        run: Test-WSMan localhost
      - name: Print EventLog
        if: always()
        run: winrm enumerate winrm/config/Listener
      - name: Print EventLog
        if: always()
        run: Get-WinEvent -ListLog *winrm*  | fl *

  agentless:
    name: Agentless
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [3.2]
    env:
      BOLT_WINDOWS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache modules
        id: modules
        uses: actions/cache@v4
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - uses: ./.github/actions/windows_agentless_setup
      - name: Run tests
        run: bundle exec rake ci:windows:agentless
